name: affiliate_sdk
description: Affiliate tracking SDK for Flutter applications
version: 1.0.0
homepage: https://github.com/your-company/affiliate-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: